using System;
using Oculus.Interaction.Input;
using Oculus.Interaction.PoseDetection;
using UnityEngine;

namespace Oculus.Interaction.Locomotion;

public class TeleportInteractor : Interactor<TeleportInteractor, TeleportInteractable>, ILocomotionEventBroadcaster
{
	public delegate bool AcceptDestinationComputer(TeleportInteractable interactable, Pose destination);

	public delegate int ComputeCandidateTiebreakerDelegate(TeleportInteractable a, TeleportInteractable b);

	public delegate TeleportInteractable ComputeCandidateDelegate(IPolyline TeleportArc, in InteractableRegistry<TeleportInteractor, TeleportInteractable>.InteractableSet interactables, ComputeCandidateTiebreakerDelegate tiebreaker, out TeleportHit hitPose);

	[SerializeField]
	[Interface(typeof(ISelector), new Type[] { })]
	[Tooltip("A selector indicating when the Interactor shouldSelect or Unselect the best available interactable.Typically when using controllers this selector is driven by the joystick value,and for hands it is driven by the index pinch value.")]
	private UnityEngine.Object _selector;

	[SerializeField]
	[Interface(typeof(IPolyline), new Type[] { })]
	[Optional(OptionalAttribute.Flag.AutoGenerated)]
	[Tooltip("Specifies the shape of the arc used for detecting available interactables.If none is provided TeleportArcGravity will be used.")]
	private UnityEngine.Object _teleportArc;

	[SerializeField]
	[Optional(OptionalAttribute.Flag.Obsolete)]
	[Tooltip("(Meters, World) The threshold below which distances to a interactable are treated as equal for the purposes of ranking.")]
	private float _equalDistanceThreshold = 0.1f;

	[SerializeField]
	[Optional(OptionalAttribute.Flag.Obsolete)]
	[Interface(typeof(IHmd), new Type[] { })]
	[Tooltip("When provided, the Interactor will perform an extra check to ensurenothing is blocking the line between the Hmd and the teleport origin")]
	private UnityEngine.Object _hmd;

	private TeleportHit _arcEnd;

	private Action<LocomotionEvent> _whenLocomotionPerformed = delegate
	{
	};

	private AcceptDestinationComputer _acceptDestination;

	private ComputeCandidateDelegate _computeCandidate;

	private ComputeCandidateTiebreakerDelegate _computeCandidateTiebreaker;

	public IPolyline TeleportArc { get; private set; }

	[Obsolete("This property is obsolete, create a ComputeCandidateDelegate if you need custom candidate computing logic")]
	public float EqualDistanceThreshold
	{
		get
		{
			return _equalDistanceThreshold;
		}
		set
		{
			_equalDistanceThreshold = value;
		}
	}

	[Obsolete("This property is obsolete, create a ComputeCandidateDelegate if you need custom candidate computing logic")]
	private IHmd Hmd { get; set; }

	public Pose ArcOrigin
	{
		get
		{
			Vector3 vector = TeleportArc.PointAtIndex(0);
			Vector3 vector2 = TeleportArc.PointAtIndex(1);
			return new Pose(vector, Quaternion.LookRotation(vector2 - vector));
		}
	}

	public TeleportHit ArcEnd => _arcEnd;

	public Pose TeleportTarget
	{
		get
		{
			Quaternion rotation = Quaternion.LookRotation(Vector3.ProjectOnPlane(ArcOrigin.forward, _arcEnd.Normal), _arcEnd.Normal);
			Pose pose = new Pose(_arcEnd.Point, rotation);
			if (base.HasInteractable)
			{
				return base.Interactable.TargetPose(pose);
			}
			return pose;
		}
	}

	public AcceptDestinationComputer AcceptDestination
	{
		get
		{
			return _acceptDestination;
		}
		set
		{
			_acceptDestination = value;
		}
	}

	public event Action<LocomotionEvent> WhenLocomotionPerformed
	{
		add
		{
			_whenLocomotionPerformed = (Action<LocomotionEvent>)Delegate.Combine(_whenLocomotionPerformed, value);
		}
		remove
		{
			_whenLocomotionPerformed = (Action<LocomotionEvent>)Delegate.Remove(_whenLocomotionPerformed, value);
		}
	}

	protected override void Awake()
	{
		base.Awake();
		if (TeleportArc == null)
		{
			TeleportArc = _teleportArc as IPolyline;
		}
		if (base.Selector == null)
		{
			base.Selector = _selector as ISelector;
		}
		Hmd = _hmd as IHmd;
		_nativeId = 5507730199525946473uL;
		_computeCandidateTiebreaker = ComputeCandidateTiebreaker;
	}

	protected override void Start()
	{
		this.BeginStart(ref _started, delegate
		{
			base.Start();
		});
		if (TeleportArc == null)
		{
			TeleportArcGravity teleportArc = base.gameObject.AddComponent<TeleportArcGravity>();
			InjectOptionalTeleportArc(teleportArc);
		}
		if (_computeCandidate == null)
		{
			GameObject gameObject = new GameObject("Default CandidateComputer");
			TeleportCandidateComputer teleportCandidateComputer = gameObject.AddComponent<TeleportCandidateComputer>();
			teleportCandidateComputer.EqualDistanceThreshold = _equalDistanceThreshold;
			if (Hmd != null)
			{
				gameObject.AddComponent<HmdOffset>().InjectAllHmdOffset(Hmd);
				teleportCandidateComputer.BlockCheckOrigin = gameObject.transform;
			}
			_computeCandidate = teleportCandidateComputer.ComputeCandidate;
		}
		this.EndStart(ref _started);
	}

	public override bool CanSelect(TeleportInteractable interactable)
	{
		Pose origin = ArcOrigin;
		float sqrMagnitude = (TeleportArc.PointAtIndex(0) - TeleportArc.PointAtIndex(TeleportArc.PointsCount - 1)).sqrMagnitude;
		if (!interactable.IsInRange(in origin, sqrMagnitude))
		{
			return false;
		}
		return base.CanSelect(interactable);
	}

	public bool HasValidDestination()
	{
		Pose teleportTarget = TeleportTarget;
		if (base.Interactable != null && base.Interactable.AllowTeleport)
		{
			if (_acceptDestination != null)
			{
				return _acceptDestination(base.Interactable, teleportTarget);
			}
			return true;
		}
		return false;
	}

	protected override void InteractableSelected(TeleportInteractable interactable)
	{
		base.InteractableSelected(interactable);
		Pose teleportTarget = TeleportTarget;
		if (!HasValidDestination())
		{
			LocomotionEvent obj = new LocomotionEvent(base.Identifier, teleportTarget, LocomotionEvent.TranslationType.None, LocomotionEvent.RotationType.None);
			_whenLocomotionPerformed(obj);
		}
		else
		{
			LocomotionEvent obj2 = new LocomotionEvent(base.Identifier, teleportTarget, interactable.EyeLevel ? LocomotionEvent.TranslationType.AbsoluteEyeLevel : LocomotionEvent.TranslationType.Absolute, interactable.FaceTargetDirection ? LocomotionEvent.RotationType.Absolute : LocomotionEvent.RotationType.None);
			_whenLocomotionPerformed(obj2);
		}
	}

	protected override TeleportInteractable ComputeCandidate()
	{
		InteractableRegistry<TeleportInteractor, TeleportInteractable>.InteractableSet interactables = Interactable<TeleportInteractor, TeleportInteractable>.Registry.List(this);
		return _computeCandidate(TeleportArc, in interactables, _computeCandidateTiebreaker, out _arcEnd);
	}

	protected override int ComputeCandidateTiebreaker(TeleportInteractable a, TeleportInteractable b)
	{
		int num = base.ComputeCandidateTiebreaker(a, b);
		if (num != 0)
		{
			return num;
		}
		return a.TieBreakerScore.CompareTo(b.TieBreakerScore);
	}

	public void InjectAllTeleportInteractor(ISelector selector)
	{
		InjectSelector(selector);
	}

	public void InjectSelector(ISelector selector)
	{
		_selector = selector as UnityEngine.Object;
		base.Selector = selector;
	}

	[Obsolete("This property is no longer in use, create a ComputeCandidateDelegate if you need custom candidate computing logic")]
	public void InjectOptionalHmd(IHmd hmd)
	{
		_hmd = hmd as UnityEngine.Object;
		Hmd = hmd;
	}

	public void InjectOptionalTeleportArc(IPolyline teleportArc)
	{
		_teleportArc = teleportArc as UnityEngine.Object;
		TeleportArc = teleportArc;
	}

	public void InjectOptionalCandidateComputer(ComputeCandidateDelegate candidateComputer)
	{
		_computeCandidate = candidateComputer;
	}
}
