using System;
using Oculus.Interaction.Input;
using UnityEngine;

namespace Oculus.Interaction.Locomotion;

public class LocomotionTurnerInteractorVisual : MonoBehaviour
{
	[SerializeField]
	private LocomotionTurnerInteractor _turner;

	[SerializeField]
	[Optional]
	private TurnerEventBroadcaster _broadcaster;

	[SerializeField]
	[Optional]
	private Transform _lookAt;

	[SerializeField]
	[Optional(OptionalAttribute.Flag.AutoGenerated)]
	private Transform _root;

	[SerializeField]
	private TurnArrowVisuals _visuals;

	[SerializeField]
	[Interface(typeof(IAxis1D), new Type[] { })]
	[Optional]
	private UnityEngine.Object _progress;

	[SerializeField]
	private float _verticalOffset = 0.02f;

	protected bool _started;

	private IAxis1D Progress { get; set; }

	public float VerticalOffset
	{
		get
		{
			return _verticalOffset;
		}
		set
		{
			_verticalOffset = value;
		}
	}

	protected virtual void Awake()
	{
		Progress = _progress as IAxis1D;
	}

	protected virtual void Start()
	{
		this.BeginStart(ref _started);
		if (_root == null)
		{
			_root = base.transform;
		}
		this.EndStart(ref _started);
	}

	protected virtual void OnEnable()
	{
		if (_started && _turner != null)
		{
			_turner.WhenStateChanged += HandleTurnerStateChanged;
			_turner.WhenPreprocessed += HandleTurnerPostprocessed;
		}
	}

	protected virtual void OnDisable()
	{
		if (_started && _turner != null)
		{
			_turner.WhenStateChanged -= HandleTurnerStateChanged;
			_turner.WhenPreprocessed -= HandleTurnerPostprocessed;
		}
	}

	private void HandleTurnerStateChanged(InteractorStateChangeArgs stateArgs)
	{
		if (stateArgs.NewState == InteractorState.Disabled)
		{
			_visuals.DisableVisuals();
		}
	}

	private void HandleTurnerPostprocessed()
	{
		if (!(_turner != null) || _turner.State != InteractorState.Disabled)
		{
			UpdatePose(_turner.MidPoint);
			_visuals.Progress = Progress.Value();
			_visuals.Value = _turner.Value();
			_visuals.FollowArrow = _broadcaster == null || _broadcaster.TurnMethod == TurnerEventBroadcaster.TurnMode.Snap;
			_visuals.HighLight = _turner.State == InteractorState.Select;
			_visuals.UpdateVisual();
		}
	}

	private void UpdatePose(Pose origin)
	{
		Vector3 vector = origin.forward;
		if (_lookAt != null)
		{
			vector = Vector3.ProjectOnPlane(origin.position - _lookAt.position, origin.up).normalized;
		}
		Vector3 position = origin.position - vector * _visuals.Radius + origin.up * _verticalOffset;
		Quaternion rotation = Quaternion.LookRotation(vector, origin.up);
		_root.SetPositionAndRotation(position, rotation);
	}

	public void InjectAllLocomotionTurnerInteractorArrowsVisual(LocomotionTurnerInteractor turner, TurnArrowVisuals visuals)
	{
		InjectTurner(turner);
		InjectVisuals(visuals);
	}

	public void InjectTurner(LocomotionTurnerInteractor turner)
	{
		_turner = turner;
	}

	public void InjectOptionalRoot(Transform root)
	{
		_root = root;
	}

	public void InjectVisuals(TurnArrowVisuals visuals)
	{
		_visuals = visuals;
	}

	public void InjectOptionalLookAt(Transform lookAt)
	{
		_lookAt = lookAt;
	}

	public void InjectOptionalProgress(IAxis1D progress)
	{
		_progress = progress as UnityEngine.Object;
		Progress = progress;
	}
}
