public enum GRAttributeType
{
	None,
	ArmorMax,
	EnergyMax,
	EnergyUseCost,
	EnergyStart,
	FlashDamage,
	BatonDamage,
	LightIntensity,
	HarvestGain,
	ShieldSize,
	HPMax,
	PatrolSpeed,
	ChaseSpeed,
	PoweredBatonDamage,
	PlayerDamage,
	PlayerShieldDamage,
	BackupSpeed,
	KnockbackMultiplier,
	RechargeRate,
	FlashStunDuration,
	DirectionalShieldDamage
}
