using System.Collections.Generic;

public static class UnityTags
{
	public static readonly string[] StringValues = new string[158]
	{
		"Untagged", "Respawn", "Finish", "EditorOnly", "MainCamera", "Player", "GameController", "SceneChanger", "PlayerOffset", "GorillaTagManager",
		"GorillaTagCollider", "GorillaPlayer", "GorillaObject", "GorillaGameManager", "GorillaCosmetic", "projectile", "FxTemporaire", "SlingshotProjectile", "SlingshotProjectileTrail", "SlingshotProjectilePlayerImpactFX",
		"SlingshotProjectileSurfaceImpactFX", "BalloonPopFX", "WorldShareableItem", "HornsSlingshotProjectile", "HornsSlingshotProjectileTrail", "HornsSlingshotProjectilePlayerImpactFX", "HornsSlingshotProjectileSurfaceImpactFX", "FryingPan", "LeafPile_ImpactFX", "BalloonPopFx",
		"CloudSlingshot_Projectile", "CloudSlingshot_ProjectileTrail", "CloudSlingshot_ProjectilePlayerImpactFX", "CloudSlingshot_ProjectileSurfaceImpactFX", "SnowballProjectile", "SnowballProjectileImpactFX", "CupidBow_Projectile", "CupidBow_ProjectileTrail", "CupidBow_ProjectileSurfaceImpactFX", "NoCrazyCheck",
		"IceSlingshot_Projectile", "IceSlingshot_ProjectileSurfaceImpactFX", "IceSlingshot_ProjectileTrail", "ElfBow_Projectile", "ElfBow_ProjectileSurfaceImpactFX", "ElfBow_ProjectileTrail", "RenderIfSmall", "DeleteOnNonBetaBuild", "DeleteOnNonDebugBuild", "FlagColoringCauldon",
		"WaterRippleEffect", "WaterSplashEffect", "FireworkMortarProjectile", "FireworkMortarProjectileImpactFX", "WaterBalloonProjectile", "WaterBalloonProjectileImpactFX", "PlayerHeadTrigger", "WizardStaff", "LurkerGhost", "HauntedObject",
		"WanderingGhost", "LavaSurfaceRock", "LavaRockProjectile", "LavaRockProjectileImpactFX", "MoltenSlingshot_Projectile", "MoltenSlingshot_ProjectileTrail", "MoltenSlingshot_ProjectileSurfaceImpactFX", "MoltenSlingshot_ProjectilePlayerImpactFX", "SpiderBow_Projectile", "SpiderBow_ProjectileTrail",
		"SpiderBow_ProjectileSurfaceImpactFX", "SpiderBow_ProjectilePlayerImpactFX", "ZoneRoot", "DontProcessMaterials", "OrnamentProjectileSurfaceImpactFX", "BucketGiftCane", "BucketGiftCoal", "BucketGiftRoll", "BucketGiftRound", "BucketGiftSquare",
		"OrnamentProjectile", "OrnamentShatterFX", "ScienceCandyProjectile", "ScienceCandyImpactFX", "PaperAirplaneProjectile", "DevilBow_Projectile", "DevilBow_ProjectileTrail", "DevilBow_ProjectileSurfaceImpactFX", "DevilBow_ProjectilePlayerImpactFX", "Fire_FX",
		"FishFood", "FishFoodImpactFX", "LeafNinjaStarProjectile", "LeafNinjaStarProjectileC1", "LeafNinjaStarProjectileC2", "SamuraiBow_Projectile", "SamuraiBow_ProjectileTrail", "SamuraiBow_ProjectileSurfaceImpactFX", "SamuraiBow_ProjectilePlayerImpactFX", "DragonSling_Projectile",
		"DragonSling_ProjectileTrail", "DragonSling_ProjectileSurfaceImpactFX", "DragonSling_ProjectilePlayerImpactFX", "Fireball_Projectile", "StealthHandTapFX", "EnvPieceTree01", "FxSnapPiecePlaced", "FxSnapPieceDisconnected", "FxSnapPieceGrabbed", "FxSnapPieceLocationLock",
		"CyberNinjaStarProjectile", "RoomLight", "SamplesInfoPanel", "GorillaHandLeft", "GorillaHandRight", "GorillaHandSocket", "PlayingCardProjectile", "RottenPumpkinProjectile", "FxSnapPieceRecycle", "FxSnapPieceDispenser",
		"AppleProjectile", "AppleProjectileSurfaceImpactFX", "RecyclerForceVolumeFX", "FxSnapPieceTooHeavy", "FxBuilderPrivatePlotClaimed", "TrickTreat_Candy", "TrickTreat_Eyeball", "TrickTreat_Bat", "TrickTreat_Bomb", "TrickTreat_SurfaceImpact",
		"TrickTreat_Bat_Impact", "TrickTreat_Bomb_Impact", "GuardianSlapFX", "GuardianSlamFX", "GuardianIdolLandedFX", "GuardianIdolFallFX", "GuardianIdolTappedFX", "VotingRockProjectile", "LeafPile_ImpactFX_Medium", "LeafPile_ImpactFX_Small",
		"WoodenSword", "WoodenShield", "FxBuilderShrink", "FxBuilderGrow", "FxSnapPieceWreathJump", "ElfLauncherElf", "RubberBandCar", "SnowPile_ImpactFX", "Firecrackers_Projectile", "PaperAirplaneSquare_Projectile",
		"SmokeBomb_Projectile", "ThrowableHeart_Projectile", "SunFlowers", "RobotCannon_Projectile", "RobotCannon_ProjectileImpact", "SmokeBomb_ExplosionEffect", "FireCracker_ExplosionEffect", "GorillaMouth"
	};

	public static readonly Dictionary<string, UnityTag> StringToTag = new Dictionary<string, UnityTag>
	{
		["Untagged"] = UnityTag.Untagged,
		["Respawn"] = UnityTag.Respawn,
		["Finish"] = UnityTag.Finish,
		["EditorOnly"] = UnityTag.EditorOnly,
		["MainCamera"] = UnityTag.MainCamera,
		["Player"] = UnityTag.Player,
		["GameController"] = UnityTag.GameController,
		["SceneChanger"] = UnityTag.SceneChanger,
		["PlayerOffset"] = UnityTag.PlayerOffset,
		["GorillaTagManager"] = UnityTag.GorillaTagManager,
		["GorillaTagCollider"] = UnityTag.GorillaTagCollider,
		["GorillaPlayer"] = UnityTag.GorillaPlayer,
		["GorillaObject"] = UnityTag.GorillaObject,
		["GorillaGameManager"] = UnityTag.GorillaGameManager,
		["GorillaCosmetic"] = UnityTag.GorillaCosmetic,
		["projectile"] = UnityTag.projectile,
		["FxTemporaire"] = UnityTag.FxTemporaire,
		["SlingshotProjectile"] = UnityTag.SlingshotProjectile,
		["SlingshotProjectileTrail"] = UnityTag.SlingshotProjectileTrail,
		["SlingshotProjectilePlayerImpactFX"] = UnityTag.SlingshotProjectilePlayerImpactFX,
		["SlingshotProjectileSurfaceImpactFX"] = UnityTag.SlingshotProjectileSurfaceImpactFX,
		["BalloonPopFX"] = UnityTag.BalloonPopFX,
		["WorldShareableItem"] = UnityTag.WorldShareableItem,
		["HornsSlingshotProjectile"] = UnityTag.HornsSlingshotProjectile,
		["HornsSlingshotProjectileTrail"] = UnityTag.HornsSlingshotProjectileTrail,
		["HornsSlingshotProjectilePlayerImpactFX"] = UnityTag.HornsSlingshotProjectilePlayerImpactFX,
		["HornsSlingshotProjectileSurfaceImpactFX"] = UnityTag.HornsSlingshotProjectileSurfaceImpactFX,
		["FryingPan"] = UnityTag.FryingPan,
		["LeafPile_ImpactFX"] = UnityTag.LeafPileImpactFX,
		["BalloonPopFx"] = UnityTag.BalloonPopFx,
		["CloudSlingshot_Projectile"] = UnityTag.CloudSlingshotProjectile,
		["CloudSlingshot_ProjectileTrail"] = UnityTag.CloudSlingshotProjectileTrail,
		["CloudSlingshot_ProjectilePlayerImpactFX"] = UnityTag.CloudSlingshotProjectilePlayerImpactFX,
		["CloudSlingshot_ProjectileSurfaceImpactFX"] = UnityTag.CloudSlingshotProjectileSurfaceImpactFX,
		["SnowballProjectile"] = UnityTag.SnowballProjectile,
		["SnowballProjectileImpactFX"] = UnityTag.SnowballProjectileImpactFX,
		["CupidBow_Projectile"] = UnityTag.CupidBowProjectile,
		["CupidBow_ProjectileTrail"] = UnityTag.CupidBowProjectileTrail,
		["CupidBow_ProjectileSurfaceImpactFX"] = UnityTag.CupidBowProjectileSurfaceImpactFX,
		["NoCrazyCheck"] = UnityTag.NoCrazyCheck,
		["IceSlingshot_Projectile"] = UnityTag.IceSlingshotProjectile,
		["IceSlingshot_ProjectileSurfaceImpactFX"] = UnityTag.IceSlingshotProjectileSurfaceImpactFX,
		["IceSlingshot_ProjectileTrail"] = UnityTag.IceSlingshotProjectileTrail,
		["ElfBow_Projectile"] = UnityTag.ElfBowProjectile,
		["ElfBow_ProjectileSurfaceImpactFX"] = UnityTag.ElfBowProjectileSurfaceImpactFX,
		["ElfBow_ProjectileTrail"] = UnityTag.ElfBowProjectileTrail,
		["RenderIfSmall"] = UnityTag.RenderIfSmall,
		["DeleteOnNonBetaBuild"] = UnityTag.DeleteOnNonBetaBuild,
		["DeleteOnNonDebugBuild"] = UnityTag.DeleteOnNonDebugBuild,
		["FlagColoringCauldon"] = UnityTag.FlagColoringCauldon,
		["WaterRippleEffect"] = UnityTag.WaterRippleEffect,
		["WaterSplashEffect"] = UnityTag.WaterSplashEffect,
		["FireworkMortarProjectile"] = UnityTag.FireworkMortarProjectile,
		["FireworkMortarProjectileImpactFX"] = UnityTag.FireworkMortarProjectileImpactFX,
		["WaterBalloonProjectile"] = UnityTag.WaterBalloonProjectile,
		["WaterBalloonProjectileImpactFX"] = UnityTag.WaterBalloonProjectileImpactFX,
		["PlayerHeadTrigger"] = UnityTag.PlayerHeadTrigger,
		["WizardStaff"] = UnityTag.WizardStaff,
		["LurkerGhost"] = UnityTag.LurkerGhost,
		["HauntedObject"] = UnityTag.HauntedObject,
		["WanderingGhost"] = UnityTag.WanderingGhost,
		["LavaSurfaceRock"] = UnityTag.LavaSurfaceRock,
		["LavaRockProjectile"] = UnityTag.LavaRockProjectile,
		["LavaRockProjectileImpactFX"] = UnityTag.LavaRockProjectileImpactFX,
		["MoltenSlingshot_Projectile"] = UnityTag.MoltenSlingshotProjectile,
		["MoltenSlingshot_ProjectileTrail"] = UnityTag.MoltenSlingshotProjectileTrail,
		["MoltenSlingshot_ProjectileSurfaceImpactFX"] = UnityTag.MoltenSlingshotProjectileSurfaceImpactFX,
		["MoltenSlingshot_ProjectilePlayerImpactFX"] = UnityTag.MoltenSlingshotProjectilePlayerImpactFX,
		["SpiderBow_Projectile"] = UnityTag.SpiderBowProjectile,
		["SpiderBow_ProjectileTrail"] = UnityTag.SpiderBowProjectileTrail,
		["SpiderBow_ProjectileSurfaceImpactFX"] = UnityTag.SpiderBowProjectileSurfaceImpactFX,
		["SpiderBow_ProjectilePlayerImpactFX"] = UnityTag.SpiderBowProjectilePlayerImpactFX,
		["ZoneRoot"] = UnityTag.ZoneRoot,
		["DontProcessMaterials"] = UnityTag.DontProcessMaterials,
		["OrnamentProjectileSurfaceImpactFX"] = UnityTag.OrnamentProjectileSurfaceImpactFX,
		["BucketGiftCane"] = UnityTag.BucketGiftCane,
		["BucketGiftCoal"] = UnityTag.BucketGiftCoal,
		["BucketGiftRoll"] = UnityTag.BucketGiftRoll,
		["BucketGiftRound"] = UnityTag.BucketGiftRound,
		["BucketGiftSquare"] = UnityTag.BucketGiftSquare,
		["OrnamentProjectile"] = UnityTag.OrnamentProjectile,
		["OrnamentShatterFX"] = UnityTag.OrnamentShatterFX,
		["ScienceCandyProjectile"] = UnityTag.ScienceCandyProjectile,
		["ScienceCandyImpactFX"] = UnityTag.ScienceCandyImpactFX,
		["PaperAirplaneProjectile"] = UnityTag.PaperAirplaneProjectile,
		["DevilBow_Projectile"] = UnityTag.DevilBowProjectile,
		["DevilBow_ProjectileTrail"] = UnityTag.DevilBowProjectileTrail,
		["DevilBow_ProjectileSurfaceImpactFX"] = UnityTag.DevilBowProjectileSurfaceImpactFX,
		["DevilBow_ProjectilePlayerImpactFX"] = UnityTag.DevilBowProjectilePlayerImpactFX,
		["Fire_FX"] = UnityTag.FireFX,
		["FishFood"] = UnityTag.FishFood,
		["FishFoodImpactFX"] = UnityTag.FishFoodImpactFX,
		["LeafNinjaStarProjectile"] = UnityTag.LeafNinjaStarProjectile,
		["LeafNinjaStarProjectileC1"] = UnityTag.LeafNinjaStarProjectileC1,
		["LeafNinjaStarProjectileC2"] = UnityTag.LeafNinjaStarProjectileC2,
		["SamuraiBow_Projectile"] = UnityTag.SamuraiBowProjectile,
		["SamuraiBow_ProjectileTrail"] = UnityTag.SamuraiBowProjectileTrail,
		["SamuraiBow_ProjectileSurfaceImpactFX"] = UnityTag.SamuraiBowProjectileSurfaceImpactFX,
		["SamuraiBow_ProjectilePlayerImpactFX"] = UnityTag.SamuraiBowProjectilePlayerImpactFX,
		["DragonSling_Projectile"] = UnityTag.DragonSlingProjectile,
		["DragonSling_ProjectileTrail"] = UnityTag.DragonSlingProjectileTrail,
		["DragonSling_ProjectileSurfaceImpactFX"] = UnityTag.DragonSlingProjectileSurfaceImpactFX,
		["DragonSling_ProjectilePlayerImpactFX"] = UnityTag.DragonSlingProjectilePlayerImpactFX,
		["Fireball_Projectile"] = UnityTag.FireballProjectile,
		["StealthHandTapFX"] = UnityTag.StealthHandTapFX,
		["EnvPieceTree01"] = UnityTag.EnvPieceTree01,
		["FxSnapPiecePlaced"] = UnityTag.FxSnapPiecePlaced,
		["FxSnapPieceDisconnected"] = UnityTag.FxSnapPieceDisconnected,
		["FxSnapPieceGrabbed"] = UnityTag.FxSnapPieceGrabbed,
		["FxSnapPieceLocationLock"] = UnityTag.FxSnapPieceLocationLock,
		["CyberNinjaStarProjectile"] = UnityTag.CyberNinjaStarProjectile,
		["RoomLight"] = UnityTag.RoomLight,
		["SamplesInfoPanel"] = UnityTag.SamplesInfoPanel,
		["GorillaHandLeft"] = UnityTag.GorillaHandLeft,
		["GorillaHandRight"] = UnityTag.GorillaHandRight,
		["GorillaHandSocket"] = UnityTag.GorillaHandSocket,
		["PlayingCardProjectile"] = UnityTag.PlayingCardProjectile,
		["RottenPumpkinProjectile"] = UnityTag.RottenPumpkinProjectile,
		["FxSnapPieceRecycle"] = UnityTag.FxSnapPieceRecycle,
		["FxSnapPieceDispenser"] = UnityTag.FxSnapPieceDispenser,
		["AppleProjectile"] = UnityTag.AppleProjectile,
		["AppleProjectileSurfaceImpactFX"] = UnityTag.AppleProjectileSurfaceImpactFX,
		["RecyclerForceVolumeFX"] = UnityTag.RecyclerForceVolumeFX,
		["FxSnapPieceTooHeavy"] = UnityTag.FxSnapPieceTooHeavy,
		["FxBuilderPrivatePlotClaimed"] = UnityTag.FxBuilderPrivatePlotClaimed,
		["TrickTreat_Candy"] = UnityTag.TrickTreatCandy,
		["TrickTreat_Eyeball"] = UnityTag.TrickTreatEyeball,
		["TrickTreat_Bat"] = UnityTag.TrickTreatBat,
		["TrickTreat_Bomb"] = UnityTag.TrickTreatBomb,
		["TrickTreat_SurfaceImpact"] = UnityTag.TrickTreatSurfaceImpact,
		["TrickTreat_Bat_Impact"] = UnityTag.TrickTreatBatImpact,
		["TrickTreat_Bomb_Impact"] = UnityTag.TrickTreatBombImpact,
		["GuardianSlapFX"] = UnityTag.GuardianSlapFX,
		["GuardianSlamFX"] = UnityTag.GuardianSlamFX,
		["GuardianIdolLandedFX"] = UnityTag.GuardianIdolLandedFX,
		["GuardianIdolFallFX"] = UnityTag.GuardianIdolFallFX,
		["GuardianIdolTappedFX"] = UnityTag.GuardianIdolTappedFX,
		["VotingRockProjectile"] = UnityTag.VotingRockProjectile,
		["LeafPile_ImpactFX_Medium"] = UnityTag.LeafPileImpactFXMedium,
		["LeafPile_ImpactFX_Small"] = UnityTag.LeafPileImpactFXSmall,
		["WoodenSword"] = UnityTag.WoodenSword,
		["WoodenShield"] = UnityTag.WoodenShield,
		["FxBuilderShrink"] = UnityTag.FxBuilderShrink,
		["FxBuilderGrow"] = UnityTag.FxBuilderGrow,
		["FxSnapPieceWreathJump"] = UnityTag.FxSnapPieceWreathJump,
		["ElfLauncherElf"] = UnityTag.ElfLauncherElf,
		["RubberBandCar"] = UnityTag.RubberBandCar,
		["SnowPile_ImpactFX"] = UnityTag.SnowPileImpactFX,
		["Firecrackers_Projectile"] = UnityTag.FirecrackersProjectile,
		["PaperAirplaneSquare_Projectile"] = UnityTag.PaperAirplaneSquareProjectile,
		["SmokeBomb_Projectile"] = UnityTag.SmokeBombProjectile,
		["ThrowableHeart_Projectile"] = UnityTag.ThrowableHeartProjectile,
		["SunFlowers"] = UnityTag.SunFlowers,
		["RobotCannon_Projectile"] = UnityTag.RobotCannonProjectile,
		["RobotCannon_ProjectileImpact"] = UnityTag.RobotCannonProjectileImpact,
		["SmokeBomb_ExplosionEffect"] = UnityTag.SmokeBombExplosionEffect,
		["FireCracker_ExplosionEffect"] = UnityTag.FireCrackerExplosionEffect,
		["GorillaMouth"] = UnityTag.GorillaMouth
	};
}
