using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text.RegularExpressions;
using Meta.XR.Util;
using UnityEngine;

[HelpURL("https://developer.oculus.com/documentation/unity/move-face-tracking/")]
[Feature(Feature.FaceTracking)]
public static class OVRCustomFaceExtensions
{
	public static OVRFaceExpressions.FaceExpression[] AutoGenerateMapping(Mesh skinnedMesh, string[] blendShapeNames, OVRFaceExpressions.FaceExpression[] faceExpressions, bool allowDuplicateMapping)
	{
		OVRFaceExpressions.FaceExpression[] array = new OVRFaceExpressions.FaceExpression[skinnedMesh.blendShapeCount];
		HashSet<string>[] array2 = new HashSet<string>[blendShapeNames.Length];
		for (int i = 0; i < blendShapeNames.Length; i++)
		{
			array2[i] = TokenizeString(blendShapeNames[i]);
		}
		HashSet<OVRFaceExpressions.FaceExpression> hashSet = new HashSet<OVRFaceExpressions.FaceExpression>();
		for (int j = 0; j < skinnedMesh.blendShapeCount; j++)
		{
			string blendShapeName = skinnedMesh.GetBlendShapeName(j);
			OVRFaceExpressions.FaceExpression faceExpression = FindBestMatch(array2, blendShapeName, faceExpressions, OVRFaceExpressions.FaceExpression.Invalid);
			if (!allowDuplicateMapping && hashSet.Contains(faceExpression) && !IsLipsToward(blendShapeName))
			{
				array[j] = OVRFaceExpressions.FaceExpression.Invalid;
				continue;
			}
			array[j] = faceExpression;
			hashSet.Add(faceExpression);
		}
		return array;
	}

	private static OVRFaceExpressions.FaceExpression FindBestMatch(HashSet<string>[] tokenizedOptions, string searchString, OVRFaceExpressions.FaceExpression[] expressions, OVRFaceExpressions.FaceExpression fallback)
	{
		searchString = searchString.Substring(searchString.LastIndexOf('.') + 1);
		HashSet<string> first = TokenizeString(searchString);
		OVRFaceExpressions.FaceExpression result = fallback;
		int num = 2;
		for (int i = 0; i < tokenizedOptions.Length; i++)
		{
			int num2 = 0;
			HashSet<string> second = tokenizedOptions[i];
			foreach (string item in first.Intersect(second))
			{
				num2 += item.Length;
			}
			if (num2 > num)
			{
				num = num2;
				result = expressions[i];
			}
		}
		return result;
	}

	private static bool IsLipsToward(string blendshapeName)
	{
		blendshapeName = blendshapeName.Substring(blendshapeName.IndexOf('.') + 1);
		switch (blendshapeName)
		{
		default:
			return blendshapeName == "lipsToward_RT";
		case "lipsToward_LB":
		case "lipsToward_RB":
		case "lipsToward_LT":
			return true;
		}
	}

	internal static HashSet<string> TokenizeString(string s)
	{
		char[] separator = new char[6] { ' ', '_', '-', ',', '.', ';' };
		IEnumerable<string> enumerable = SplitCamelCase(s).Split(separator).Concat(s.Split(separator));
		HashSet<string> hashSet = new HashSet<string>();
		foreach (string item in enumerable)
		{
			string text = item.ToLowerInvariant();
			if (text == "left" || text == "l")
			{
				hashSet.Add("L");
			}
			if (text == "right" || text == "r")
			{
				hashSet.Add("R");
			}
			hashSet.Add(text);
		}
		return hashSet;
	}

	private static string SplitCamelCase(string input)
	{
		return Regex.Replace(input, "([A-Z])", " $1", RegexOptions.Compiled).Trim();
	}

	public static void AutoMapBlendshapes(this OVRCustomFace customFace)
	{
		OVRCustomFace.RetargetingType retargetingType = customFace.retargetingType;
		SkinnedMeshRenderer component = customFace.GetComponent<SkinnedMeshRenderer>();
		try
		{
			OVRFaceExpressions.FaceExpression[] array = retargetingType switch
			{
				OVRCustomFace.RetargetingType.OculusFace => OculusFaceAutoGenerateMapping(component.sharedMesh, customFace._allowDuplicateMapping), 
				OVRCustomFace.RetargetingType.Custom => CustomAutoGeneratedMapping(customFace, component.sharedMesh, customFace._allowDuplicateMapping), 
				_ => throw new InvalidEnumArgumentException("Invalid RetargetingType"), 
			};
			if (array != null)
			{
				if (customFace._mappings == null || customFace._mappings.Length != component.sharedMesh.blendShapeCount)
				{
					customFace._mappings = new OVRFaceExpressions.FaceExpression[component.sharedMesh.blendShapeCount];
				}
				for (int i = 0; i < component.sharedMesh.blendShapeCount; i++)
				{
					customFace._mappings[i] = array[i];
				}
			}
		}
		catch (Exception ex)
		{
			Debug.LogError("Auto Map Face Error: " + ex.Message);
		}
	}

	public static void ClearBlendshapes(this OVRCustomFace customFace)
	{
		SkinnedMeshRenderer component = customFace.GetComponent<SkinnedMeshRenderer>();
		for (int i = 0; i < component.sharedMesh.blendShapeCount; i++)
		{
			customFace._mappings[i] = OVRFaceExpressions.FaceExpression.Invalid;
		}
	}

	internal static OVRFaceExpressions.FaceExpression[] OculusFaceAutoGenerateMapping(Mesh sharedMesh, bool allowDuplicateMapping)
	{
		string[] names = Enum.GetNames(typeof(OVRFaceExpressions.FaceExpression));
		OVRFaceExpressions.FaceExpression[] faceExpressions = (OVRFaceExpressions.FaceExpression[])Enum.GetValues(typeof(OVRFaceExpressions.FaceExpression));
		return AutoGenerateMapping(sharedMesh, names, faceExpressions, allowDuplicateMapping);
	}

	internal static OVRFaceExpressions.FaceExpression[] CustomAutoGeneratedMapping(OVRCustomFace customFace, Mesh sharedMesh, bool allowDuplicateMapping)
	{
		var (blendShapeNames, faceExpressions) = customFace.GetCustomBlendShapeNameAndExpressionPairs();
		return AutoGenerateMapping(sharedMesh, blendShapeNames, faceExpressions, allowDuplicateMapping);
	}
}
