namespace Meta.Voice.TelemetryUtilities;

public enum RuntimeTelemetryPoint
{
	MicOn,
	ListeningStarted,
	AudioBlockSent,
	PartialResponseReceived,
	FullResponseReceived,
	FirstPartialTranscriptionReceivedByClient,
	FullTranscriptionReceivedByClient,
	FullUserTranscriptionSentToServer,
	FirstPartialTranscriptionReceivedFromClient,
	FullUserTranscriptionReceivedFromClient,
	FullUserTranscriptionSentFromServer,
	FirstPartialTextResponseSentToServer,
	FullTextResponseSentToServer,
	PartialTTSSent,
	FullTTSSent,
	PartialTTSAudioReceived,
	FinalTTSAudioReceived,
	FirstPartialAudioDecode,
	FinalAudioDecode,
	FirstPartialAudioSentToClient,
	FinalAudioSentToClient,
	FirstPartialAudioFromServer,
	FinalAudioFromServer,
	PlaybackStarted,
	PlaybackStopped,
	TtsLoadBegin,
	TtsLoadComplete,
	ListeningStopped,
	FinalAudioSamplesEmpty,
	FinalAudioEventsEmpty
}
