using System;
using System.Collections.Generic;
using Oculus.Interaction.Grab;
using Oculus.Interaction.GrabAPI;
using Oculus.Interaction.Input;
using UnityEngine;
using UnityEngine.Serialization;

namespace Oculus.Interaction.HandGrab;

[Serializable]
public class HandGrabInteractable : PointerInteractable<HandGrabInteractor, HandGrabInteractable>, IHandGrabInteractable, IRelativeToRef, IRigidbodyRef, ICollidersRef
{
	[Tooltip("The Rigidbody of the object.")]
	[SerializeField]
	private Rigidbody _rigidbody;

	[Tooltip("The PhysicsGrabbable used when you grab the object.")]
	[SerializeField]
	[Optional(OptionalAttribute.Flag.Obsolete)]
	[Obsolete("Use Grabbable and/or RigidbodyKinematicLocker instead")]
	private PhysicsGrabbable _physicsGrabbable;

	[Tooltip("Forces a release on all other grabbing interactors when grabbed by a new interactor.")]
	[SerializeField]
	private bool _resetGrabOnGrabsUpdated = true;

	[Tooltip("A PoseMeasureParameters used to modify the score of a pose.")]
	[SerializeField]
	[Optional]
	private PoseMeasureParameters _scoringModifier = new PoseMeasureParameters(0.8f);

	[SerializeField]
	[Optional]
	[Range(0f, 1f)]
	[Tooltip("Defines the slippiness threshold so the interactor can slide along the interactable based on thestrength of the grip. GrabSurfaces are required to slide. At min slippiness = 0, the interactor never moves.")]
	private float _slippiness;

	[Tooltip("The grab types that the object supports.")]
	[Space]
	[SerializeField]
	private GrabTypeFlags _supportedGrabTypes = GrabTypeFlags.All;

	[Tooltip("Uses the state of the fingers to define when a pinch grab starts and ends.")]
	[SerializeField]
	private GrabbingRule _pinchGrabRules = GrabbingRule.DefaultPinchRule;

	[Tooltip("Uses the state of the fingers to define when a palm grab starts and ends.")]
	[SerializeField]
	private GrabbingRule _palmGrabRules = GrabbingRule.DefaultPalmRule;

	[Header("Movement", order = -1)]
	[Tooltip("Determines how the object will move when selected.")]
	[SerializeField]
	[Interface(typeof(IMovementProvider), new Type[] { })]
	[Optional(OptionalAttribute.Flag.AutoGenerated)]
	private UnityEngine.Object _movementProvider;

	[Tooltip("Determines when the hand will be aligned with the object.")]
	[SerializeField]
	private HandAlignType _handAligment = HandAlignType.AlignOnGrab;

	[Tooltip(" ")]
	[SerializeField]
	[Optional(OptionalAttribute.Flag.DontHide)]
	[FormerlySerializedAs("_handGrabPoints")]
	private List<HandGrabPose> _handGrabPoses = new List<HandGrabPose>();

	private GrabPoseFinder _grabPoseFinder;

	private static CollisionInteractionRegistry<HandGrabInteractor, HandGrabInteractable> _registry;

	public Rigidbody Rigidbody => _rigidbody;

	public bool ResetGrabOnGrabsUpdated
	{
		get
		{
			return _resetGrabOnGrabsUpdated;
		}
		set
		{
			_resetGrabOnGrabsUpdated = value;
		}
	}

	public float Slippiness
	{
		get
		{
			return _slippiness;
		}
		set
		{
			_slippiness = value;
		}
	}

	private IMovementProvider MovementProvider { get; set; }

	public HandAlignType HandAlignment
	{
		get
		{
			return _handAligment;
		}
		set
		{
			_handAligment = value;
		}
	}

	public List<HandGrabPose> HandGrabPoses => _handGrabPoses;

	public Transform RelativeTo => _rigidbody.transform;

	public PoseMeasureParameters ScoreModifier => _scoringModifier;

	public GrabTypeFlags SupportedGrabTypes => _supportedGrabTypes;

	public GrabbingRule PinchGrabRules => _pinchGrabRules;

	public GrabbingRule PalmGrabRules => _palmGrabRules;

	public Collider[] Colliders { get; private set; }

	public bool UsesHandPose => _grabPoseFinder.UsesHandPose;

	protected virtual void Reset()
	{
		InjectRigidbody(GetComponentInParent<Rigidbody>());
		InjectOptionalPointableElement(GetComponentInParent<Grabbable>());
	}

	protected override void Awake()
	{
		base.Awake();
		MovementProvider = _movementProvider as IMovementProvider;
	}

	protected override void Start()
	{
		this.BeginStart(ref _started, delegate
		{
			base.Start();
		});
		if (_registry == null)
		{
			_registry = new CollisionInteractionRegistry<HandGrabInteractor, HandGrabInteractable>();
			SetRegistry(_registry);
		}
		Colliders = Rigidbody.GetComponentsInChildren<Collider>();
		if (MovementProvider == null)
		{
			IMovementProvider provider = base.gameObject.AddComponent<MoveTowardsTargetProvider>();
			InjectOptionalMovementProvider(provider);
		}
		_grabPoseFinder = new GrabPoseFinder(_handGrabPoses, RelativeTo);
		this.EndStart(ref _started);
	}

	public IMovement GenerateMovement(in Pose from, in Pose to)
	{
		IMovement movement = MovementProvider.CreateMovement();
		movement.StopAndSetPose(from);
		movement.MoveTo(to);
		return movement;
	}

	[Obsolete("Use Grabbable instead")]
	public void ApplyVelocities(Vector3 linearVelocity, Vector3 angularVelocity)
	{
		if (!(_physicsGrabbable == null))
		{
			_physicsGrabbable.ApplyVelocities(linearVelocity, angularVelocity);
		}
	}

	public bool CalculateBestPose(Pose userPose, float handScale, Handedness handedness, ref HandGrabResult result)
	{
		CalculateBestPose(in userPose, Pose.identity, RelativeTo, handScale, handedness, ref result);
		return true;
	}

	public void CalculateBestPose(in Pose userPose, in Pose offset, Transform relativeTo, float handScale, Handedness handedness, ref HandGrabResult result)
	{
		if (!_grabPoseFinder.FindBestPose(in userPose, in offset, handScale, handedness, _scoringModifier, ref result))
		{
			Pose pose = PoseUtils.Multiply(in userPose, in offset);
			result.HasHandPose = false;
			result.Score = GrabPoseHelper.CollidersScore(pose.position, Colliders, out var hitPoint);
			Pose to = new Pose(hitPoint, pose.rotation);
			result.RelativePose = RelativeTo.Delta(in to);
		}
	}

	public bool SupportsHandedness(Handedness handedness)
	{
		return _grabPoseFinder.SupportsHandedness(handedness);
	}

	public void InjectAllHandGrabInteractable(GrabTypeFlags supportedGrabTypes, Rigidbody rigidbody, GrabbingRule pinchGrabRules, GrabbingRule palmGrabRules)
	{
		InjectSupportedGrabTypes(supportedGrabTypes);
		InjectRigidbody(rigidbody);
		InjectPinchGrabRules(pinchGrabRules);
		InjectPalmGrabRules(palmGrabRules);
	}

	public void InjectSupportedGrabTypes(GrabTypeFlags supportedGrabTypes)
	{
		_supportedGrabTypes = supportedGrabTypes;
	}

	public void InjectPinchGrabRules(GrabbingRule pinchGrabRules)
	{
		_pinchGrabRules = pinchGrabRules;
	}

	public void InjectPalmGrabRules(GrabbingRule palmGrabRules)
	{
		_palmGrabRules = palmGrabRules;
	}

	public void InjectRigidbody(Rigidbody rigidbody)
	{
		_rigidbody = rigidbody;
	}

	public void InjectOptionalScoreModifier(PoseMeasureParameters scoreModifier)
	{
		_scoringModifier = scoreModifier;
	}

	[Obsolete("Use Grabbable instead")]
	public void InjectOptionalPhysicsGrabbable(PhysicsGrabbable physicsGrabbable)
	{
		_physicsGrabbable = physicsGrabbable;
	}

	public void InjectOptionalHandGrabPoses(List<HandGrabPose> handGrabPoses)
	{
		_handGrabPoses = handGrabPoses;
	}

	public void InjectOptionalMovementProvider(IMovementProvider provider)
	{
		_movementProvider = provider as UnityEngine.Object;
		MovementProvider = provider;
	}

	IMovement IHandGrabInteractable.GenerateMovement(in Pose from, in Pose to)
	{
		return GenerateMovement(in from, in to);
	}

	void IHandGrabInteractable.CalculateBestPose(in Pose userPose, in Pose offset, Transform relativeTo, float handScale, Handedness handedness, ref HandGrabResult result)
	{
		CalculateBestPose(in userPose, in offset, relativeTo, handScale, handedness, ref result);
	}
}
