using System;
using System.Collections.Generic;
using Oculus.Interaction.Grab;
using Oculus.Interaction.GrabAPI;
using Oculus.Interaction.Input;
using UnityEngine;
using UnityEngine.Serialization;

namespace Oculus.Interaction.HandGrab;

[Serializable]
public class DistanceHandGrabInteractable : PointerInteractable<DistanceHandGrabInteractor, DistanceHandGrabInteractable>, IHandGrabInteractable, IRelativeToRef, IRigidbodyRef, ICollidersRef
{
	[SerializeField]
	private Rigidbody _rigidbody;

	[SerializeField]
	[Optional(OptionalAttribute.Flag.Obsolete)]
	[Obsolete("Use Grabbable and/or RigidbodyKinematicLocker instead")]
	private PhysicsGrabbable _physicsGrabbable;

	[SerializeField]
	private bool _resetGrabOnGrabsUpdated = true;

	[Space]
	[SerializeField]
	[Optional]
	[Range(0f, 1f)]
	[Tooltip("Defines the slippiness threshold so the interactor can slide along the interactable based on thestrength of the grip. GrabSurfaces are required to slide. At min slippiness = 0, the interactor never moves.")]
	private float _slippiness;

	[Space]
	[SerializeField]
	private GrabTypeFlags _supportedGrabTypes = GrabTypeFlags.Pinch;

	[SerializeField]
	private GrabbingRule _pinchGrabRules = GrabbingRule.DefaultPinchRule;

	[SerializeField]
	private GrabbingRule _palmGrabRules = GrabbingRule.DefaultPalmRule;

	[SerializeField]
	[Interface(typeof(IMovementProvider), new Type[] { })]
	[Optional(OptionalAttribute.Flag.AutoGenerated)]
	private UnityEngine.Object _movementProvider;

	[SerializeField]
	private HandAlignType _handAligment = HandAlignType.AlignOnGrab;

	[SerializeField]
	[Optional(OptionalAttribute.Flag.DontHide)]
	[FormerlySerializedAs("_handGrabPoints")]
	private List<HandGrabPose> _handGrabPoses = new List<HandGrabPose>();

	private GrabPoseFinder _grabPoseFinder;

	private readonly PoseMeasureParameters SCORE_MODIFIER = new PoseMeasureParameters(1f);

	public Rigidbody Rigidbody => _rigidbody;

	public bool ResetGrabOnGrabsUpdated
	{
		get
		{
			return _resetGrabOnGrabsUpdated;
		}
		set
		{
			_resetGrabOnGrabsUpdated = value;
		}
	}

	public float Slippiness
	{
		get
		{
			return _slippiness;
		}
		set
		{
			_slippiness = value;
		}
	}

	public IMovementProvider MovementProvider { get; set; }

	public HandAlignType HandAlignment
	{
		get
		{
			return _handAligment;
		}
		set
		{
			_handAligment = value;
		}
	}

	public Transform RelativeTo => _rigidbody.transform;

	public GrabTypeFlags SupportedGrabTypes => _supportedGrabTypes;

	public GrabbingRule PinchGrabRules => _pinchGrabRules;

	public GrabbingRule PalmGrabRules => _palmGrabRules;

	public List<HandGrabPose> HandGrabPoses => _handGrabPoses;

	public Collider[] Colliders { get; private set; }

	public bool UsesHandPose => _grabPoseFinder.UsesHandPose;

	protected virtual void Reset()
	{
		if (TryGetComponent<HandGrabInteractable>(out var component))
		{
			InjectAllDistanceHandGrabInteractable(component.SupportedGrabTypes, component.Rigidbody, component.PinchGrabRules, component.PalmGrabRules);
			InjectOptionalHandGrabPoses(new List<HandGrabPose>(component.HandGrabPoses));
			InjectOptionalPointableElement(component.PointableElement);
		}
		else
		{
			InjectRigidbody(GetComponentInParent<Rigidbody>());
			InjectOptionalPointableElement(GetComponentInParent<Grabbable>());
		}
	}

	protected override void Awake()
	{
		base.Awake();
		MovementProvider = _movementProvider as IMovementProvider;
	}

	protected override void Start()
	{
		this.BeginStart(ref _started, delegate
		{
			base.Start();
		});
		Colliders = Rigidbody.GetComponentsInChildren<Collider>();
		if (MovementProvider == null)
		{
			MoveTowardsTargetProvider provider = base.gameObject.AddComponent<MoveTowardsTargetProvider>();
			InjectOptionalMovementProvider(provider);
		}
		_grabPoseFinder = new GrabPoseFinder(_handGrabPoses, RelativeTo);
		this.EndStart(ref _started);
	}

	public IMovement GenerateMovement(in Pose from, in Pose to)
	{
		IMovement movement = MovementProvider.CreateMovement();
		movement.StopAndSetPose(from);
		movement.MoveTo(to);
		return movement;
	}

	[Obsolete("Use Grabbable instead")]
	public void ApplyVelocities(Vector3 linearVelocity, Vector3 angularVelocity)
	{
		if (!(_physicsGrabbable == null))
		{
			_physicsGrabbable.ApplyVelocities(linearVelocity, angularVelocity);
		}
	}

	public bool CalculateBestPose(Pose userPose, float handScale, Handedness handedness, ref HandGrabResult result)
	{
		CalculateBestPose(in userPose, Pose.identity, RelativeTo, handScale, handedness, ref result);
		return true;
	}

	public void CalculateBestPose(in Pose userPose, in Pose offset, Transform relativeTo, float handScale, Handedness handedness, ref HandGrabResult result)
	{
		if (!_grabPoseFinder.FindBestPose(in userPose, in offset, handScale, handedness, SCORE_MODIFIER, ref result))
		{
			Pose pose = PoseUtils.Multiply(in userPose, in offset);
			result.HasHandPose = false;
			result.Score = new GrabPoseScore(pose.position, base.transform.position);
			result.RelativePose = new Pose(RelativeTo.Delta(base.transform).position, Quaternion.Inverse(RelativeTo.rotation) * pose.rotation);
		}
	}

	public bool SupportsHandedness(Handedness handedness)
	{
		return _grabPoseFinder.SupportsHandedness(handedness);
	}

	public void InjectAllDistanceHandGrabInteractable(GrabTypeFlags supportedGrabTypes, Rigidbody rigidbody, GrabbingRule pinchGrabRules, GrabbingRule palmGrabRules)
	{
		InjectSupportedGrabTypes(supportedGrabTypes);
		InjectRigidbody(rigidbody);
		InjectPinchGrabRules(pinchGrabRules);
		InjectPalmGrabRules(palmGrabRules);
	}

	[Obsolete("Use Grabbable instead")]
	public void InjectOptionalPhysicsGrabbable(PhysicsGrabbable physicsObject)
	{
		_physicsGrabbable = physicsObject;
	}

	public void InjectSupportedGrabTypes(GrabTypeFlags supportedGrabTypes)
	{
		_supportedGrabTypes = supportedGrabTypes;
	}

	public void InjectPinchGrabRules(GrabbingRule pinchGrabRules)
	{
		_pinchGrabRules = pinchGrabRules;
	}

	public void InjectPalmGrabRules(GrabbingRule palmGrabRules)
	{
		_palmGrabRules = palmGrabRules;
	}

	public void InjectRigidbody(Rigidbody rigidbody)
	{
		_rigidbody = rigidbody;
	}

	public void InjectOptionalHandGrabPoses(List<HandGrabPose> handGrabPoses)
	{
		_handGrabPoses = handGrabPoses;
	}

	public void InjectOptionalMovementProvider(IMovementProvider provider)
	{
		_movementProvider = provider as UnityEngine.Object;
		MovementProvider = provider;
	}

	IMovement IHandGrabInteractable.GenerateMovement(in Pose from, in Pose to)
	{
		return GenerateMovement(in from, in to);
	}

	void IHandGrabInteractable.CalculateBestPose(in Pose userPose, in Pose offset, Transform relativeTo, float handScale, Handedness handedness, ref HandGrabResult result)
	{
		CalculateBestPose(in userPose, in offset, relativeTo, handScale, handedness, ref result);
	}
}
