namespace UnityEngine.XR.OpenXR.NativeTypes;

public enum XrStructureType : uint
{
	XR_TYPE_UNKNOWN = 0u,
	XR_TYPE_SWAPCHAIN_CREATE_INFO = 9u,
	XR_TYPE_COMPOSITION_LAYER_PROJECTION = 35u,
	XR_TYPE_COMPOSITION_LAYER_QUAD = 36u,
	XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW = 48u,
	XR_TYPE_COMPOSITION_LAYER_CUBE_KHR = 1000006000u,
	XR_TYPE_COMPOSITION_LAYER_CYLINDER_KHR = 1000017000u,
	XR_TYPE_COMPOSITION_LAYER_EQUIRECT_KHR = 1000018000u,
	XR_TYPE_COMPOSITION_LAYER_EQUIRECT2_KHR = 1000091000u
}
