using System;

namespace UnityEngine.XR.OpenXR.NativeTypes;

[Flags]
public enum XrSwapchainUsageFlags : ulong
{
	XR_SWAPCHAIN_USAGE_COLOR_ATTACHMENT_BIT = 1uL,
	XR_SWAPCHAIN_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT = 2uL,
	XR_SWAPCHAIN_USAGE_UNORDERED_ACCESS_BIT = 4uL,
	XR_SWAPCHAIN_USAGE_TRANSFER_SRC_BIT = 8uL,
	XR_SWAPCHAIN_USAGE_TRANSFER_DST_BIT = 0x10uL,
	XR_SWAPCHAIN_USAGE_SAMPLED_BIT = 0x20uL,
	XR_SWAPCHAIN_USAGE_MUTABLE_FORMAT_BIT = 0x40uL,
	XR_SWAPCHAIN_USAGE_INPUT_ATTACHMENT_BIT_MND = 0x80uL,
	XR_SWAPCHAIN_USAGE_INPUT_ATTACHMENT_BIT_KHR = 0x80uL
}
