using System.Collections.Generic;
using Oculus.Interaction.UnityCanvas;
using UnityEngine;

namespace Oculus.Interaction.Samples;

public class InteractableObjectLabel : MonoBehaviour
{
	private enum LabelState
	{
		Hidden,
		FocusCheck,
		Focused,
		HideCheck,
		Used
	}

	[Tooltip("The positions of these transforms are used to check if the user is facing the object")]
	public List<Transform> viewTargets;

	[Tooltip("The possible positions for the label, the component always selected the one that has the highest y position component")]
	public List<Transform> labelPositions;

	[Tooltip("The position between the left and right cameras")]
	[Optional(OptionalAttribute.Flag.AutoGenerated)]
	public Transform playerHead;

	[Tooltip("This group should contain all the interactions in the object, and when one is triggered the label is hidden")]
	public InteractableGroupView interactableGroup;

	private Vector3 _startScale;

	[Space(10f)]
	[Tooltip("Canvas group at the root of the label canvas, used to make the canvas completely transparent")]
	public CanvasGroup group;

	public float alphaAnimationSpeed;

	public float focusDelay;

	public float hideDelay;

	public float alignmentThreshold;

	public float minScale;

	public float positionAnimationSpeed;

	[Space(10f)]
	public Mesh quadMesh;

	public Material quadMaterial;

	public RectTransform canvasTransform;

	public CanvasRenderTexture canvasTexture;

	private LabelState _currentState;

	private float _targetAlpha;

	private float _currentAlpha;

	private float _startTime;

	private MaterialPropertyBlock _block;

	private Transform _quadTransform;

	private MeshRenderer _quadRenderer;

	private Vector3 currentLabelPosition;

	protected bool _started;

	private void Start()
	{
		_targetAlpha = 0f;
		this.BeginStart(ref _started);
		if (playerHead == null)
		{
			playerHead = Camera.main.transform;
		}
		CreateTextureQuad();
		_startScale = _quadTransform.localScale;
		_block = new MaterialPropertyBlock();
		this.EndStart(ref _started);
	}

	private void CreateTextureQuad()
	{
		GameObject gameObject = new GameObject();
		gameObject.name = "CanvasTexture";
		_quadTransform = gameObject.transform;
		_quadTransform.parent = base.transform;
		_quadTransform.localScale = new Vector3
		{
			x = canvasTransform.sizeDelta.x * canvasTransform.localScale.x,
			y = canvasTransform.sizeDelta.y * canvasTransform.localScale.y,
			z = 1f
		};
		gameObject.AddComponent<MeshFilter>().sharedMesh = quadMesh;
		_quadRenderer = gameObject.AddComponent<MeshRenderer>();
		_quadRenderer.sharedMaterial = quadMaterial;
	}

	private void OnEnable()
	{
		interactableGroup.WhenStateChanged += InteractableStateChange;
	}

	private void OnDisable()
	{
		interactableGroup.WhenStateChanged -= InteractableStateChange;
	}

	private void SetTargetAlpha()
	{
		switch (_currentState)
		{
		case LabelState.Hidden:
			_targetAlpha = 0f;
			break;
		case LabelState.FocusCheck:
			_targetAlpha = 0f;
			break;
		case LabelState.Focused:
			_targetAlpha = 1f;
			break;
		case LabelState.HideCheck:
			_targetAlpha = 1f;
			break;
		case LabelState.Used:
			_targetAlpha = 0f;
			break;
		}
	}

	private float MaximizedDotView()
	{
		if (viewTargets == null)
		{
			return 0f;
		}
		float num = -1f;
		foreach (Transform viewTarget in viewTargets)
		{
			Vector3 rhs = Vector3.Normalize(viewTarget.position - playerHead.position);
			float b = Vector3.Dot(playerHead.forward, rhs);
			num = Mathf.Max(num, b);
		}
		return num;
	}

	private void StateTransition()
	{
		float num = MaximizedDotView();
		switch (_currentState)
		{
		case LabelState.Hidden:
			if (num >= alignmentThreshold)
			{
				_currentState = LabelState.FocusCheck;
				_startTime = Time.time;
			}
			break;
		case LabelState.FocusCheck:
			if (num < alignmentThreshold)
			{
				_currentState = LabelState.Hidden;
			}
			else if (Time.time - _startTime >= focusDelay)
			{
				_currentState = LabelState.Focused;
			}
			break;
		case LabelState.Focused:
			if (num <= alignmentThreshold)
			{
				_currentState = LabelState.HideCheck;
				_startTime = Time.time;
			}
			break;
		case LabelState.HideCheck:
			if (num > alignmentThreshold)
			{
				_currentState = LabelState.Focused;
			}
			else if (Time.time - _startTime >= hideDelay)
			{
				_currentState = LabelState.Hidden;
			}
			break;
		}
	}

	private void InteractableStateChange(InteractableStateChangeArgs args)
	{
		switch (args.NewState)
		{
		case InteractableState.Select:
			_currentState = LabelState.Used;
			break;
		case InteractableState.Normal:
			if (_currentState == LabelState.Used)
			{
				_currentState = LabelState.Hidden;
			}
			break;
		}
	}

	private Vector3 FindHighestLabelPosition()
	{
		if (labelPositions == null)
		{
			return base.transform.position;
		}
		int num = -1;
		float num2 = base.transform.position.y;
		for (int i = 0; i < labelPositions.Count; i++)
		{
			float y = labelPositions[i].position.y;
			if (y > num2)
			{
				num = i;
				num2 = y;
			}
		}
		if (num == -1)
		{
			return base.transform.position;
		}
		return labelPositions[num].position;
	}

	private void UpdateLabelTransform()
	{
		_startScale = new Vector3
		{
			x = canvasTransform.sizeDelta.x * canvasTransform.localScale.x,
			y = canvasTransform.sizeDelta.y * canvasTransform.localScale.y,
			z = 1f
		};
		Vector3 b = FindHighestLabelPosition();
		currentLabelPosition = Vector3.Lerp(currentLabelPosition, b, positionAnimationSpeed);
		float b2 = Vector3.Distance(currentLabelPosition, playerHead.position);
		float num = Mathf.Max(minScale, b2);
		_quadTransform.localScale = _startScale * num;
		float num2 = _quadTransform.localScale.y * 0.5f;
		_quadTransform.position = currentLabelPosition + _quadTransform.up * num2;
		_quadTransform.LookAt(playerHead.position);
		_quadTransform.localRotation *= Quaternion.Euler(0f, 180f, 0f);
	}

	private void Update()
	{
		UpdateLabelTransform();
		SetTargetAlpha();
		StateTransition();
		_currentAlpha = Mathf.Lerp(_currentAlpha, _targetAlpha, alphaAnimationSpeed);
		group.alpha = Mathf.Clamp01(_currentAlpha);
		_block.SetTexture("_MainTex", canvasTexture.Texture);
		_quadRenderer.SetPropertyBlock(_block);
	}
}
