using System.Linq;
using TMPro;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

namespace Oculus.Interaction.Samples;

public class DropDownGroup : MonoBehaviour
{
	[SerializeField]
	[Optional(OptionalAttribute.Flag.AutoGenerated)]
	[Tooltip("ToggleGroup for all the options in the dropdown. It will be enforced to dissallow off-state and be referenced in all toggles. If none provided it will be searched in the hierarchy under this component.")]
	private ToggleGroup _toggleGroup;

	[SerializeField]
	[Optional]
	[Tooltip("The toggle for the headerIt will be closed automatically when an option is selected.")]
	private Toggle _headerToggle;

	[SerializeField]
	[Optional(OptionalAttribute.Flag.AutoGenerated)]
	[Tooltip("Toggles for all options in the dropdown, if none provided it will be searched in the hierarchy under the toggle group.")]
	private Toggle[] _toggles;

	public UnityEvent<int> WhenSelectionChanged;

	[Header("Header visuals")]
	[SerializeField]
	[Optional(OptionalAttribute.Flag.DontHide)]
	[Tooltip("Title label in the header")]
	private TextMeshProUGUI _title;

	[SerializeField]
	[ConditionalHide("_title", null, ConditionalHideAttribute.DisplayMode.HideIfTrue)]
	[Tooltip("Name of the Gameobject holding the title in each option.")]
	private string _titleName = "Title";

	[SerializeField]
	[Optional(OptionalAttribute.Flag.DontHide)]
	[Tooltip("Subtitle label in the header.")]
	private TextMeshProUGUI _subtitle;

	[SerializeField]
	[ConditionalHide("_subtitle", null, ConditionalHideAttribute.DisplayMode.HideIfTrue)]
	[Tooltip("Name of the Gameobject holding the subtitle in each option.")]
	private string _subtitleName = "Subtitle";

	[SerializeField]
	[Optional(OptionalAttribute.Flag.DontHide)]
	[Tooltip("Image for the icon in the header.")]
	private Image _icon;

	[SerializeField]
	[ConditionalHide("_icon", null, ConditionalHideAttribute.DisplayMode.HideIfTrue)]
	[Tooltip("Name of the Gameobject holding the icon in each option.")]
	private string _iconName = "Icon";

	private int _selectedIndex = -1;

	private UnityAction<bool>[] _toggleActions;

	protected bool _started;

	public TextMeshProUGUI Title
	{
		get
		{
			return _title;
		}
		set
		{
			_title = value;
		}
	}

	public string TitleName
	{
		get
		{
			return _titleName;
		}
		set
		{
			_titleName = value;
		}
	}

	public TextMeshProUGUI Subtitle
	{
		get
		{
			return _subtitle;
		}
		set
		{
			_subtitle = value;
		}
	}

	public string SubtitleName
	{
		get
		{
			return _subtitleName;
		}
		set
		{
			_subtitleName = value;
		}
	}

	public Image Icon
	{
		get
		{
			return _icon;
		}
		set
		{
			_icon = value;
		}
	}

	public string IconName
	{
		get
		{
			return _iconName;
		}
		set
		{
			_iconName = value;
		}
	}

	public int SelectedIndex
	{
		get
		{
			return _selectedIndex;
		}
		private set
		{
			if (_selectedIndex != value)
			{
				_selectedIndex = value;
				WhenSelectionChanged.Invoke(_selectedIndex);
			}
		}
	}

	public Toggle SelectedToggle
	{
		get
		{
			if (_selectedIndex < 0)
			{
				return null;
			}
			return _toggles[_selectedIndex];
		}
	}

	protected virtual void Reset()
	{
		_toggleGroup = GetComponentInChildren<ToggleGroup>();
	}

	protected virtual void Start()
	{
		this.BeginStart(ref _started);
		if (_toggleGroup == null)
		{
			_toggleGroup = GetComponentInChildren<ToggleGroup>();
		}
		if (_toggles == null || _toggles.Length == 0)
		{
			Toggle[] componentsInChildren = _toggleGroup.transform.GetComponentsInChildren<Toggle>();
			_toggles = componentsInChildren.Where((Toggle toggle) => toggle.group == _toggleGroup).ToArray();
		}
		InitializeToggleActions();
		InitializeToggleGroup();
		this.EndStart(ref _started);
	}

	protected virtual void OnEnable()
	{
		if (_started)
		{
			for (int i = 0; i < _toggles.Length; i++)
			{
				_toggles[i].onValueChanged.AddListener(_toggleActions[i]);
			}
			ForceUpdateSelectedIndex();
		}
	}

	protected virtual void OnDisable()
	{
		if (_started)
		{
			for (int i = 0; i < _toggles.Length; i++)
			{
				_toggles[i].onValueChanged.RemoveListener(_toggleActions[i]);
			}
		}
	}

	private void ForceUpdateSelectedIndex()
	{
		for (int i = 0; i < _toggles.Length; i++)
		{
			if (_toggles[i].isOn)
			{
				SelectedIndex = i;
				break;
			}
		}
		HandleToggleChanged(isOn: true, SelectedIndex);
	}

	private void InitializeToggleActions()
	{
		_toggleActions = new UnityAction<bool>[_toggles.Length];
		for (int i = 0; i < _toggleActions.Length; i++)
		{
			int toggleIndex = i;
			_toggleActions[i] = delegate(bool isOn)
			{
				HandleToggleChanged(isOn, toggleIndex);
				if (isOn)
				{
					_headerToggle.isOn = false;
				}
			};
		}
	}

	private void InitializeToggleGroup()
	{
		_toggleGroup.allowSwitchOff = false;
		Toggle[] toggles = _toggles;
		foreach (Toggle toggle in toggles)
		{
			if (!(toggle.group == _toggleGroup))
			{
				if (toggle.group != null)
				{
					toggle.group.UnregisterToggle(toggle);
				}
				toggle.group = _toggleGroup;
				_toggleGroup.RegisterToggle(toggle);
			}
		}
		_toggleGroup.EnsureValidState();
	}

	private void HandleToggleChanged(bool isOn, int index)
	{
		if (isOn && index >= 0)
		{
			Toggle toggle = _toggles[index];
			if (_title != null && _title.gameObject.activeSelf && TryGetChildComponent<TextMeshProUGUI>(toggle.transform, _titleName, out var component))
			{
				_title.text = component.text;
			}
			if (_subtitle != null && _subtitle.gameObject.activeSelf && TryGetChildComponent<TextMeshProUGUI>(toggle.transform, _subtitleName, out var component2))
			{
				_subtitle.text = component2.text;
			}
			if (_icon != null && _icon.gameObject.activeSelf && TryGetChildComponent<Image>(toggle.transform, _iconName, out var component3))
			{
				_icon.sprite = component3.sprite;
			}
			SelectedIndex = index;
		}
	}

	private static bool TryGetChildComponent<TComponent>(Transform root, string childName, out TComponent component) where TComponent : Component
	{
		Transform transform = root.FindChildRecursive(childName);
		if (transform != null && transform.gameObject.activeSelf && transform.TryGetComponent<TComponent>(out component))
		{
			return true;
		}
		component = null;
		return false;
	}

	public void InjectAllDropDownShowSelectedItem(Toggle[] toggles, ToggleGroup toggleGroup)
	{
		InjectToggles(toggles);
		InjectToggleGroup(toggleGroup);
	}

	public void InjectToggles(Toggle[] toggles)
	{
		_toggles = toggles;
	}

	public void InjectToggleGroup(ToggleGroup toggleGroup)
	{
		_toggleGroup = toggleGroup;
	}
}
