using System;
using Meta.XR.Util;
using UnityEngine;

namespace Oculus.Interaction.Input;

[Feature(Feature.Interaction)]
public class FromOVRHandDataSource : DataSource<HandDataAsset>
{
	[Header("OVR Data Source")]
	[SerializeField]
	[Interface(typeof(IOVRCameraRigRef), new Type[] { })]
	private UnityEngine.Object _cameraRigRef;

	[SerializeField]
	private bool _processLateUpdates;

	[Header("Shared Configuration")]
	[SerializeField]
	private Handedness _handedness;

	[SerializeField]
	[Optional(OptionalAttribute.Flag.AutoGenerated)]
	private OVRHand _ovrHand;

	[SerializeField]
	[Interface(typeof(ITrackingToWorldTransformer), new Type[] { })]
	private UnityEngine.Object _trackingToWorldTransformer;

	private ITrackingToWorldTransformer TrackingToWorldTransformer;

	[SerializeField]
	[Interface(typeof(IHandSkeletonProvider), new Type[] { })]
	private UnityEngine.Object _handSkeletonProvider;

	private IHandSkeletonProvider HandSkeletonProvider;

	private readonly HandDataAsset _handDataAsset = new HandDataAsset();

	private float _lastHandScale;

	private HandDataSourceConfig _config;

	private IOVRCameraRigRef CameraRigRef;

	public bool ProcessLateUpdates
	{
		get
		{
			return _processLateUpdates;
		}
		set
		{
			_processLateUpdates = value;
		}
	}

	protected override HandDataAsset DataAsset => _handDataAsset;

	public static Quaternion WristFixupRotation { get; } = new Quaternion(0f, 1f, 0f, 0f);

	private HandDataSourceConfig Config
	{
		get
		{
			if (_config != null)
			{
				return _config;
			}
			_config = new HandDataSourceConfig
			{
				Handedness = _handedness
			};
			return _config;
		}
	}

	protected virtual void Awake()
	{
		TrackingToWorldTransformer = _trackingToWorldTransformer as ITrackingToWorldTransformer;
		CameraRigRef = _cameraRigRef as IOVRCameraRigRef;
		HandSkeletonProvider = _handSkeletonProvider as IHandSkeletonProvider;
		UpdateConfig();
	}

	protected override void Start()
	{
		this.BeginStart(ref _started, delegate
		{
			base.Start();
		});
		if (_ovrHand == null)
		{
			_ovrHand = ((_handedness == Handedness.Left) ? CameraRigRef.LeftHand : CameraRigRef.RightHand);
		}
		UpdateConfig();
		_ = OVRRuntimeSettings.GetRuntimeSettings().HandSkeletonVersion;
		this.EndStart(ref _started);
	}

	protected override void OnEnable()
	{
		base.OnEnable();
		if (_started)
		{
			CameraRigRef.WhenInputDataDirtied += HandleInputDataDirtied;
		}
	}

	protected override void OnDisable()
	{
		if (_started)
		{
			CameraRigRef.WhenInputDataDirtied -= HandleInputDataDirtied;
		}
		base.OnDisable();
		MarkInputDataRequiresUpdate();
	}

	private void HandleInputDataDirtied(bool isLateUpdate)
	{
		if (!isLateUpdate || _processLateUpdates)
		{
			MarkInputDataRequiresUpdate();
		}
	}

	private void UpdateConfig()
	{
		Config.Handedness = _handedness;
		Config.TrackingToWorldTransformer = TrackingToWorldTransformer;
		Config.HandSkeleton = HandSkeletonProvider[_handedness];
	}

	protected override void UpdateData()
	{
		_handDataAsset.Config = Config;
		_handDataAsset.IsDataValid = true;
		_handDataAsset.IsConnected = false;
		if (_ovrHand != null && _ovrHand.isActiveAndEnabled && base.isActiveAndEnabled)
		{
			OVRSkeleton.SkeletonPoseData skeletonPoseData = ((OVRSkeleton.IOVRSkeletonDataProvider)_ovrHand).GetSkeletonPoseData();
			_handDataAsset.IsConnected = skeletonPoseData.IsDataValid && skeletonPoseData.RootScale > 0f;
			if (!_handDataAsset.IsConnected)
			{
				if (_lastHandScale <= 0f)
				{
					skeletonPoseData.IsDataValid = false;
				}
				else
				{
					skeletonPoseData.RootScale = _lastHandScale;
				}
			}
			else
			{
				_lastHandScale = skeletonPoseData.RootScale;
			}
			if (skeletonPoseData.IsDataValid && _handDataAsset.IsConnected)
			{
				UpdateDataPoses(skeletonPoseData);
				return;
			}
		}
		_handDataAsset.IsConnected = false;
		_handDataAsset.IsTracked = false;
		_handDataAsset.RootPoseOrigin = PoseOrigin.None;
		_handDataAsset.PointerPoseOrigin = PoseOrigin.None;
		_handDataAsset.IsHighConfidence = false;
		for (int i = 0; i < 5; i++)
		{
			_handDataAsset.IsFingerPinching[i] = false;
			_handDataAsset.IsFingerHighConfidence[i] = false;
		}
	}

	private void UpdateDataPoses(OVRSkeleton.SkeletonPoseData poseData)
	{
		_handDataAsset.HandScale = poseData.RootScale;
		_handDataAsset.IsTracked = _ovrHand.IsTracked;
		_handDataAsset.IsHighConfidence = poseData.IsDataHighConfidence;
		_handDataAsset.IsDominantHand = _ovrHand.IsDominantHand;
		_handDataAsset.RootPoseOrigin = (_handDataAsset.IsTracked ? PoseOrigin.RawTrackedPose : PoseOrigin.None);
		for (int i = 0; i < 5; i++)
		{
			OVRHand.HandFinger finger = (OVRHand.HandFinger)i;
			bool fingerIsPinching = _ovrHand.GetFingerIsPinching(finger);
			_handDataAsset.IsFingerPinching[i] = fingerIsPinching;
			bool flag = _ovrHand.GetFingerConfidence(finger) == OVRHand.TrackingConfidence.High;
			_handDataAsset.IsFingerHighConfidence[i] = flag;
			float fingerPinchStrength = _ovrHand.GetFingerPinchStrength(finger);
			_handDataAsset.FingerPinchStrength[i] = fingerPinchStrength;
		}
		_handDataAsset.Root = new Pose
		{
			position = poseData.RootPose.Position.FromFlippedZVector3f(),
			rotation = poseData.RootPose.Orientation.FromFlippedZQuatf()
		};
		if (_ovrHand.IsPointerPoseValid)
		{
			_handDataAsset.PointerPoseOrigin = PoseOrigin.RawTrackedPose;
			_handDataAsset.PointerPose = new Pose(_ovrHand.PointerPose.localPosition, _ovrHand.PointerPose.localRotation);
		}
		else
		{
			_handDataAsset.PointerPoseOrigin = PoseOrigin.None;
		}
		float num = ((_handDataAsset.HandScale > 0f) ? (1f / _handDataAsset.HandScale) : 0f);
		OVRPlugin.Skeleton2 ovrSkeleton = ((_handedness == Handedness.Left) ? OVRSkeletonData.LeftSkeleton : OVRSkeletonData.RightSkeleton);
		for (int j = 0; j < 26; j++)
		{
			Pose to = new Pose(poseData.BoneTranslations[j].FromFlippedZVector3f(), poseData.BoneRotations[j].FromFlippedZQuatf());
			Pose pose = PoseUtils.Delta(in _handDataAsset.Root, in to);
			pose.position *= num;
			_handDataAsset.JointPoses[j] = pose;
			_handDataAsset.JointRadii[j] = HandSkeletonOVR.GetBoneRadius(in ovrSkeleton, j);
		}
		HandJointUtils.WristJointPosesToLocalRotations(_handDataAsset.JointPoses, ref _handDataAsset.Joints);
	}

	public void InjectAllFromOVRHandDataSource(UpdateModeFlags updateMode, IDataSource updateAfter, Handedness handedness, ITrackingToWorldTransformer trackingToWorldTransformer, IHandSkeletonProvider handSkeletonProvider)
	{
		InjectAllDataSource(updateMode, updateAfter);
		InjectHandedness(handedness);
		InjectTrackingToWorldTransformer(trackingToWorldTransformer);
		InjectHandSkeletonProvider(handSkeletonProvider);
	}

	public void InjectHandedness(Handedness handedness)
	{
		_handedness = handedness;
	}

	public void InjectTrackingToWorldTransformer(ITrackingToWorldTransformer trackingToWorldTransformer)
	{
		_trackingToWorldTransformer = trackingToWorldTransformer as UnityEngine.Object;
		TrackingToWorldTransformer = trackingToWorldTransformer;
	}

	public void InjectHandSkeletonProvider(IHandSkeletonProvider handSkeletonProvider)
	{
		_handSkeletonProvider = handSkeletonProvider as UnityEngine.Object;
		HandSkeletonProvider = handSkeletonProvider;
	}

	public void InjectOptionalOVRHand(OVRHand ovrHand)
	{
		_ovrHand = ovrHand;
	}
}
