namespace Viveport.Internal;

internal enum ELeaderboardUploadScoreMethod
{
	k_ELeaderboardUploadScoreMethodNone,
	k_ELeaderboardUploadScoreMethodKeepBest,
	k_ELeaderboardUploadScoreMethodForceUpdate
}
