namespace Valve.VR;

public enum SteamVR_Skeleton_JointIndexEnum
{
	root = 0,
	wrist = 1,
	thumbMetacarpal = 2,
	thumbProximal = 2,
	thumbMiddle = 3,
	thumbDistal = 4,
	thumbTip = 5,
	indexMetacarpal = 6,
	indexProximal = 7,
	indexMiddle = 8,
	indexDistal = 9,
	indexTip = 10,
	middleMetacarpal = 11,
	middleProximal = 12,
	middleMiddle = 13,
	middleDistal = 14,
	middleTip = 15,
	ringMetacarpal = 16,
	ringProximal = 17,
	ringMiddle = 18,
	ringDistal = 19,
	ringTip = 20,
	pinkyMetacarpal = 21,
	pinkyProximal = 22,
	pinkyMiddle = 23,
	pinkyDistal = 24,
	pinkyTip = 25,
	thumbAux = 26,
	indexAux = 27,
	middleAux = 28,
	ringAux = 29,
	pinkyAux = 30
}
