namespace UnityEngine.Rendering.Universal;

internal enum URPProfileId
{
	UniversalRenderTotal,
	UpdateVolumeFramework,
	RenderCameraStack,
	AdditionalLightsShadow,
	ColorGradingLUT,
	CopyColor,
	CopyDepth,
	DrawDepthNormalPrepass,
	DepthPrepass,
	UpdateReflectionProbeAtlas,
	DrawOpaqueObjects,
	DrawTransparentObjects,
	DrawScreenSpaceUI,
	RecordRenderGraph,
	LightCookies,
	MainLightShadow,
	ResolveShadows,
	SSAO,
	StopNaNs,
	SMAA,
	GaussianDepthOfField,
	BokehDepthOfField,
	TemporalAA,
	MotionBlur,
	PaniniProjection,
	UberPostProcess,
	Bloom,
	LensFlareDataDrivenComputeOcclusion,
	LensFlareDataDriven,
	LensFlareScreenSpace,
	DrawMotionVectors,
	DrawFullscreen,
	[HideInDebugUI]
	RG_SetupPostFX,
	[HideInDebugUI]
	RG_StopNaNs,
	[HideInDebugUI]
	RG_SMAAMaterialSetup,
	[HideInDebugUI]
	RG_SMAAEdgeDetection,
	[HideInDebugUI]
	RG_SMAABlendWeight,
	[HideInDebugUI]
	RG_SMAANeighborhoodBlend,
	[HideInDebugUI]
	RG_SetupDoF,
	[HideInDebugUI]
	RG_DOFComputeCOC,
	[HideInDebugUI]
	RG_DOFDownscalePrefilter,
	[HideInDebugUI]
	RG_DOFBlurH,
	[HideInDebugUI]
	RG_DOFBlurV,
	[HideInDebugUI]
	RG_DOFBlurBokeh,
	[HideInDebugUI]
	RG_DOFPostFilter,
	[HideInDebugUI]
	RG_DOFComposite,
	[HideInDebugUI]
	RG_TAA,
	[HideInDebugUI]
	RG_TAACopyHistory,
	[HideInDebugUI]
	RG_MotionBlur,
	[HideInDebugUI]
	RG_BloomSetup,
	[HideInDebugUI]
	RG_BloomPrefilter,
	[HideInDebugUI]
	RG_BloomDownsample,
	[HideInDebugUI]
	RG_BloomUpsample,
	[HideInDebugUI]
	RG_UberPostSetupBloomPass,
	[HideInDebugUI]
	RG_UberPost,
	[HideInDebugUI]
	RG_FinalSetup,
	[HideInDebugUI]
	RG_FinalFSRScale,
	[HideInDebugUI]
	RG_FinalBlit,
	BlitFinalToBackBuffer,
	DrawSkybox
}
