using System.Buffers;
using UnityEngine;

namespace Oculus.Interaction;

public class GrabFreePhysicsTransformer : MonoBehaviour, ITransformer
{
	[Tooltip("Strength of the velocity applied during fixed update")]
	[SerializeField]
	private float _velocityFactor = 60f;

	[Tooltip("Strength of the angular velocity applied during fixed update")]
	[SerializeField]
	private float _angularVelocityFactor = 0.6f;

	[Tooltip("Maximum delta for the linear velocity applied during fixed update")]
	[SerializeField]
	private float _maxLinearDelta = 100f;

	[Tooltip("Maximum delta for the angular velocity applied during fixed update")]
	[SerializeField]
	private float _maxAngularDelta = 200f;

	[SerializeField]
	[Optional(OptionalAttribute.Flag.AutoGenerated)]
	[Tooltip("Rigidbody to which the velocity will be applied.")]
	private Rigidbody _rigidbody;

	private IGrabbable _grabbable;

	private Pose _grabDeltaInLocalSpace;

	private Quaternion _lastRotation = Quaternion.identity;

	private GrabFreeTransformer.GrabPointDelta[] _deltas;

	private bool _isTransforming;

	private Vector3 _targetPosition;

	private Quaternion _targetRotation;

	public float VelocityFactor
	{
		get
		{
			return _velocityFactor;
		}
		set
		{
			_velocityFactor = value;
		}
	}

	public float AngularVelocityFactor
	{
		get
		{
			return _angularVelocityFactor;
		}
		set
		{
			_angularVelocityFactor = value;
		}
	}

	public float MaxLinearDelta
	{
		get
		{
			return _maxLinearDelta;
		}
		set
		{
			_maxLinearDelta = value;
		}
	}

	public float MaxAngularDelta
	{
		get
		{
			return _maxAngularDelta;
		}
		set
		{
			_maxAngularDelta = value;
		}
	}

	protected virtual void Reset()
	{
		_rigidbody = GetComponent<Rigidbody>();
	}

	public void Initialize(IGrabbable grabbable)
	{
		_grabbable = grabbable;
		if (_rigidbody == null)
		{
			_rigidbody = _grabbable.Transform.GetComponent<Rigidbody>();
		}
	}

	public void BeginTransform()
	{
		int count = _grabbable.GrabPoints.Count;
		_deltas = ArrayPool<GrabFreeTransformer.GrabPointDelta>.Shared.Rent(count);
		GrabFreeTransformer.InitializeDeltas(count, _grabbable.GrabPoints, ref _deltas);
		Vector3 centroid = GrabFreeTransformer.GetCentroid(_grabbable.GrabPoints);
		Transform transform = _grabbable.Transform;
		_grabDeltaInLocalSpace = new Pose(transform.InverseTransformVector(centroid - transform.position), transform.rotation);
		_lastRotation = Quaternion.identity;
		_targetRotation = _rigidbody.rotation;
		_targetPosition = _rigidbody.position;
		_isTransforming = true;
	}

	public void UpdateTransform()
	{
		if (_isTransforming)
		{
			int count = _grabbable.GrabPoints.Count;
			Transform transform = _grabbable.Transform;
			Vector3 vector = GrabFreeTransformer.UpdateTransformerPointData(_grabbable.GrabPoints, ref _deltas);
			_lastRotation = GrabFreeTransformer.UpdateRotation(count, _deltas) * _lastRotation;
			_targetRotation = _lastRotation * _grabDeltaInLocalSpace.rotation;
			_targetPosition = vector - transform.TransformVector(_grabDeltaInLocalSpace.position);
		}
	}

	public void EndTransform()
	{
		_isTransforming = false;
		ArrayPool<GrabFreeTransformer.GrabPointDelta>.Shared.Return(_deltas);
		_deltas = null;
	}

	private void FixedUpdate()
	{
		if (_isTransforming)
		{
			ApplyVelocity(_targetPosition, _targetRotation);
		}
	}

	private void ApplyVelocity(Vector3 targetPosition, Quaternion targetRotation)
	{
		Vector3 target = (targetPosition - _rigidbody.transform.position) * _velocityFactor;
		if (!float.IsNaN(target.x))
		{
			_rigidbody.velocity = Vector3.MoveTowards(_rigidbody.velocity, target, _maxLinearDelta);
		}
		(targetRotation * Quaternion.Inverse(_rigidbody.transform.rotation)).ToAngleAxis(out var angle, out var axis);
		if (angle > 180f)
		{
			angle -= 360f;
		}
		Vector3 target2 = angle * axis * _angularVelocityFactor;
		if (!Mathf.Approximately(angle, 0f) && !float.IsNaN(target2.x))
		{
			_rigidbody.angularVelocity = Vector3.MoveTowards(_rigidbody.angularVelocity, target2, _maxAngularDelta);
		}
	}

	public void InjectOptionalRigidbody(Rigidbody rigidbody)
	{
		_rigidbody = rigidbody;
	}
}
