using System;
using UnityEngine;

namespace Oculus.Interaction;

public class OptionalAttribute : PropertyAttribute
{
	[Flags]
	public enum Flag
	{
		None = 0,
		AutoGenerated = 1,
		DontHide = 2,
		Obsolete = 4
	}

	public Flag Flags { get; private set; }

	public OptionalAttribute()
	{
	}

	public OptionalAttribute(Flag flags)
	{
		Flags = flags;
	}
}
