using System;
using System.Collections.Generic;
using Oculus.Interaction.Throw;
using UnityEngine;
using UnityEngine.Pool;

namespace Oculus.Interaction;

public class Grabbable : PointableElement, IGrabbable, ITimeConsumer
{
	private class ThrowWhenUnselected : ITimeConsumer, IDisposable
	{
		private Rigidbody _rigidbody;

		private IPointable _pointable;

		private HashSet<int> _selectors;

		private Func<float> _timeProvider = () => Time.time;

		private static IObjectPool<RANSACVelocity> _ransacVelocityPool = new ObjectPool<RANSACVelocity>(() => new RANSACVelocity(10, 2), null, null, null, collectionCheck: false, 2);

		private static IObjectPool<HashSet<int>> _selectorsPool = new ObjectPool<HashSet<int>>(() => new HashSet<int>(), null, delegate(HashSet<int> s)
		{
			s.Clear();
		}, null, collectionCheck: false, 2);

		private RANSACVelocity _ransacVelocity;

		private Pose _prevPose = Pose.identity;

		private float _prevTime;

		private bool _isHighConfidence = true;

		public void SetTimeProvider(Func<float> timeProvider)
		{
			_timeProvider = timeProvider;
		}

		public ThrowWhenUnselected(Rigidbody rigidbody, IPointable pointable)
		{
			_rigidbody = rigidbody;
			_pointable = pointable;
			_pointable.WhenPointerEventRaised += HandlePointerEventRaised;
		}

		public void Dispose()
		{
			_pointable.WhenPointerEventRaised -= HandlePointerEventRaised;
		}

		private void AddSelection(int selectorId)
		{
			if (_selectors == null)
			{
				Initialize();
			}
			_selectors.Add(selectorId);
		}

		private void RemoveSelection(int selectorId, bool canThrow)
		{
			_selectors.Remove(selectorId);
			if (_selectors.Count == 0)
			{
				if (canThrow)
				{
					Process(saveAsPreviousFrame: false);
					LoadThrowVelocities();
				}
				Teardown();
			}
		}

		private void HandlePointerEventRaised(PointerEvent evt)
		{
			switch (evt.Type)
			{
			case PointerEventType.Select:
				AddSelection(evt.Identifier);
				break;
			case PointerEventType.Move:
				if (_selectors != null && _selectors.Contains(evt.Identifier))
				{
					Process(saveAsPreviousFrame: true);
					MarkFrameConfidence(evt.Identifier);
				}
				break;
			case PointerEventType.Cancel:
				RemoveSelection(evt.Identifier, canThrow: false);
				break;
			case PointerEventType.Unselect:
				MarkFrameConfidence(evt.Identifier);
				RemoveSelection(evt.Identifier, canThrow: true);
				break;
			}
		}

		private void Initialize()
		{
			_selectors = _selectorsPool.Get();
			_ransacVelocity = _ransacVelocityPool.Get();
			_ransacVelocity.Initialize();
		}

		private void Teardown()
		{
			_selectorsPool.Release(_selectors);
			_selectors = null;
			_ransacVelocityPool.Release(_ransacVelocity);
			_ransacVelocity = null;
		}

		private void MarkFrameConfidence(int emitterKey)
		{
			if (_isHighConfidence && HandTrackingConfidenceProvider.TryGetTrackingConfidence(emitterKey, out var isTrackingHighConfidence) && !isTrackingHighConfidence)
			{
				_isHighConfidence = false;
			}
		}

		private void Process(bool saveAsPreviousFrame)
		{
			float num = _timeProvider();
			Pose pose = _rigidbody.transform.GetPose();
			if (num > _prevTime || !saveAsPreviousFrame)
			{
				float time = (saveAsPreviousFrame ? _prevTime : num);
				_isHighConfidence &= pose.position != _prevPose.position;
				_ransacVelocity.Process(pose, time, _isHighConfidence);
				_isHighConfidence = true;
			}
			_prevTime = num;
			_prevPose = pose;
		}

		private void LoadThrowVelocities()
		{
			_ransacVelocity.GetVelocities(out var velocity, out var torque);
			_rigidbody.velocity = velocity;
			_rigidbody.angularVelocity = torque;
		}
	}

	[Tooltip("A One Grab...Transformer component, which should be attached to the grabbable object. Defaults to One Grab Free Transformer. If you set the Two Grab Transformer property and still want to use one hand for grabs, you must set this property as well.")]
	[SerializeField]
	[Interface(typeof(ITransformer), new Type[] { })]
	[Optional(OptionalAttribute.Flag.AutoGenerated)]
	private UnityEngine.Object _oneGrabTransformer;

	[Tooltip("A Two Grab...Transformer component, which should be attached to the grabbable object. If you set this property but also want to use one hand for grabs, you must set the One Grab Transformer property.")]
	[SerializeField]
	[Interface(typeof(ITransformer), new Type[] { })]
	[Optional(OptionalAttribute.Flag.AutoGenerated)]
	private UnityEngine.Object _twoGrabTransformer;

	[Tooltip("The target transform of the Grabbable. If unassigned, the transform of this GameObject will be used.")]
	[SerializeField]
	[Optional(OptionalAttribute.Flag.AutoGenerated)]
	private Transform _targetTransform;

	[Tooltip("The maximum number of grab points. Can be either -1 (unlimited), 1, or 2.")]
	[SerializeField]
	[Min(-1f)]
	private int _maxGrabPoints = -1;

	[Header("Physics")]
	[SerializeField]
	[Optional(OptionalAttribute.Flag.DontHide)]
	[Tooltip("Use this rigidbody to control its physics properties while grabbing.")]
	private Rigidbody _rigidbody;

	[SerializeField]
	[Tooltip("Locks the referenced rigidbody to a kinematic while selected.")]
	private bool _kinematicWhileSelected = true;

	[SerializeField]
	[Tooltip("Applies throwing velocities to the rigidbody when fully released.")]
	private bool _throwWhenUnselected = true;

	private Func<float> _timeProvider = () => Time.time;

	private ITransformer _activeTransformer;

	private ITransformer OneGrabTransformer;

	private ITransformer TwoGrabTransformer;

	private ThrowWhenUnselected _throw;

	private bool _isKinematicLocked;

	public int MaxGrabPoints
	{
		get
		{
			return _maxGrabPoints;
		}
		set
		{
			_maxGrabPoints = value;
		}
	}

	public Transform Transform => _targetTransform;

	public List<Pose> GrabPoints => _selectingPoints;

	public void SetTimeProvider(Func<float> timeProvider)
	{
		_timeProvider = timeProvider;
		if (_throw != null)
		{
			_throw.SetTimeProvider(timeProvider);
		}
	}

	protected virtual void Reset()
	{
		_rigidbody = GetComponent<Rigidbody>();
	}

	protected override void Awake()
	{
		base.Awake();
		OneGrabTransformer = _oneGrabTransformer as ITransformer;
		TwoGrabTransformer = _twoGrabTransformer as ITransformer;
	}

	protected override void Start()
	{
		this.BeginStart(ref _started, delegate
		{
			base.Start();
		});
		if (_targetTransform == null)
		{
			_targetTransform = base.transform;
		}
		if (_oneGrabTransformer != null)
		{
			OneGrabTransformer.Initialize(this);
		}
		if (_twoGrabTransformer != null)
		{
			TwoGrabTransformer.Initialize(this);
		}
		if (OneGrabTransformer == null && TwoGrabTransformer == null)
		{
			GenerateTransformer().Initialize(this);
		}
		if (_rigidbody != null && _throwWhenUnselected)
		{
			_throw = new ThrowWhenUnselected(_rigidbody, this);
			_throw.SetTimeProvider(_timeProvider);
		}
		this.EndStart(ref _started);
	}

	protected override void OnDisable()
	{
		if (_started)
		{
			EndTransform();
		}
		base.OnDisable();
	}

	protected virtual void OnDestroy()
	{
		if (_throw != null)
		{
			_throw.Dispose();
			_throw = null;
		}
	}

	private ITransformer GenerateTransformer()
	{
		ITransformer transformer = base.gameObject.AddComponent<GrabFreeTransformer>();
		InjectOptionalOneGrabTransformer(transformer);
		InjectOptionalTwoGrabTransformer(transformer);
		return transformer;
	}

	public override void ProcessPointerEvent(PointerEvent evt)
	{
		switch (evt.Type)
		{
		case PointerEventType.Select:
			EndTransform();
			break;
		case PointerEventType.Unselect:
			ForceMove(evt);
			EndTransform();
			break;
		case PointerEventType.Cancel:
			EndTransform();
			break;
		}
		base.ProcessPointerEvent(evt);
		switch (evt.Type)
		{
		case PointerEventType.Select:
			BeginTransform();
			break;
		case PointerEventType.Unselect:
			BeginTransform();
			break;
		case PointerEventType.Move:
			UpdateTransform();
			break;
		}
	}

	protected override void PointableElementUpdated(PointerEvent evt)
	{
		UpdateKinematicLock(base.SelectingPointsCount > 0);
		base.PointableElementUpdated(evt);
	}

	private void UpdateKinematicLock(bool isGrabbing)
	{
		if (!(_rigidbody == null) && _kinematicWhileSelected)
		{
			if (!_isKinematicLocked && isGrabbing)
			{
				_isKinematicLocked = true;
				_rigidbody.LockKinematic();
			}
			else if (_isKinematicLocked && !isGrabbing)
			{
				_isKinematicLocked = false;
				_rigidbody.UnlockKinematic();
			}
		}
	}

	private void ForceMove(PointerEvent releaseEvent)
	{
		PointerEvent evt = new PointerEvent(releaseEvent.Identifier, PointerEventType.Move, releaseEvent.Pose, releaseEvent.Data);
		ProcessPointerEvent(evt);
	}

	private void BeginTransform()
	{
		EndTransform();
		int num = _selectingPoints.Count;
		if (_maxGrabPoints != -1)
		{
			num = Mathf.Min(num, _maxGrabPoints);
		}
		switch (num)
		{
		case 1:
			_activeTransformer = OneGrabTransformer;
			break;
		case 2:
			_activeTransformer = TwoGrabTransformer;
			break;
		default:
			_activeTransformer = null;
			break;
		}
		if (_activeTransformer != null)
		{
			_activeTransformer.BeginTransform();
		}
	}

	private void UpdateTransform()
	{
		if (_activeTransformer != null)
		{
			_activeTransformer.UpdateTransform();
		}
	}

	private void EndTransform()
	{
		if (_activeTransformer != null)
		{
			_activeTransformer.EndTransform();
			_activeTransformer = null;
		}
	}

	public void InjectOptionalOneGrabTransformer(ITransformer transformer)
	{
		_oneGrabTransformer = transformer as UnityEngine.Object;
		OneGrabTransformer = transformer;
	}

	public void InjectOptionalTwoGrabTransformer(ITransformer transformer)
	{
		_twoGrabTransformer = transformer as UnityEngine.Object;
		TwoGrabTransformer = transformer;
	}

	public void InjectOptionalTargetTransform(Transform targetTransform)
	{
		_targetTransform = targetTransform;
	}

	public void InjectOptionalRigidbody(Rigidbody rigidbody)
	{
		_rigidbody = rigidbody;
	}

	public void InjectOptionalThrowWhenUnselected(bool throwWehenUnselected)
	{
		_throwWhenUnselected = throwWehenUnselected;
	}

	public void InjectOptionalKinematicWhileSelected(bool kinematicWhileSelected)
	{
		_kinematicWhileSelected = kinematicWhileSelected;
	}
}
